// Actions
export const SESSION_INIT_CONTROLLER = 'SESSION_INIT_CONTROLLER';
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3';

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';
