// Actions
export const SESSION_INIT_CONTROLLER = 'SESSION_INIT_CONTROLLER';
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3';

export const CONTROLLER_INIT = 'CONTROLLER_INIT';
export const CONTROLLER_LOAD_COLLATERAL_FACTOR = 'CONTROLLER_LOAD_COLLATERAL_FACTOR';
export const CONTROLLER_LOAD_LIQUIDATION_FACTOR = 'CONTROLLER_LOAD_LIQUIDATION_FACTOR';
export const CONTROLLER_LOAD_MARKETS = 'CONTROLLER_LOAD_MARKETS';
export const CONTROLLER_CREATE_MARKET = 'CONTROLLER_CREATE_MARKET';
export const CONTROLLER_SET_COLLATERAL_FACTOR = 'CONTROLLER_SET_COLLATERAL_FACTOR';
export const CONTROLLER_SET_LIQUIDATION_FACTOR = 'CONTROLLER_SET_LIQUIDATION_FACTOR';

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';
export const CONTROLLER_SET_PROPERTY = 'CONTROLLER_SET_PROPERTY';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';
